feat: cleaned up and upgraded deps

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -1,26 +1,32 @@
-FROM node:20-slim
-ARG GIT_URL
-ARG GIT_BRANCH
-ARG HOME_DIR
+# Build stage
+FROM node:20-slim AS builder
+ARG GIT_URL=https://github.com/christokur/github-cognito-openid-wrapper
+ARG GIT_BRANCH=master
 
-# Override the entrypoint with /bin/sh
-ENTRYPOINT ["/bin/sh", "-c"]
-
-RUN apt-get update
-RUN apt-get install -y --no-install-recommends \
+RUN apt-get update && apt-get install -y --no-install-recommends \
   git \
   ca-certificates \
   openssh-client \
   python3 \
-  build-essential
+  build-essential \
+  && rm -rf /var/lib/apt/lists/*
 
-RUN bash -c "[ -e /usr/bin/python ] || ln -s /usr/bin/python3 /usr/bin/python"
+# Clone and build the application
 RUN git clone --depth 1 --branch ${GIT_BRANCH} ${GIT_URL}
 WORKDIR /github-cognito-openid-wrapper
 
-# Copy .npmrc from the host's home directory if it exists
-COPY ${HOME_DIR}/.npmrc ./.npmrc
+# Copy and verify .npmrc
+COPY .npmrc /root/.npmrc
+RUN ls -la /root/.npmrc || (echo ".npmrc not found in /root/.npmrc!" && exit 1)
 
-RUN npm ci
-RUN npm run build
-RUN mv dist-lambda /asset
+RUN npm ci && \
+    npm run build && \
+    mv dist-lambda /asset
+
+# Final stage
+FROM node:20-slim
+WORKDIR /
+COPY --from=builder /asset /asset
+
+# Set the entrypoint
+ENTRYPOINT ["/bin/sh", "-c"]
